import type { Metadata } from 'next';

import './globals.css';
import '@/app/globals.css';
import '@fontsource/inter';

import Navigation from '@/components/layouts/Navigation';
import Footer from '@/components/layouts/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className="bg-white">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
